spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: student
    url: jdbc:mysql://localhost:3306/dev
    password: student
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000


server:
    error:
      include-message: always
      include-binding-errors: always
